spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/mariadb
    driverClassName: org.mariadb.jdbc.Driver
    username: mariadb
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    # Hibernate ddl auto (create, create-drop, validate, update)

  mail:
    host: smtp.gmail.com
    port: 587
    username: angellachoi0709@gmail.com
    password: nfwistcfjnmyfkqe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE